### ISSUE TITLE
Extract social media accounts

### ISSUE THREAD

**Issue by makusu2005** [dmitriiweb/extract-emails#11]
Hi!

Thanks for this awesome project. I've already used it for the extraction of emails, but can this also be used for the extraction of social media (LinkedIn) accounts? 

Thanks!

**Comment by dmitriiweb** [comment]
Hi @makusu2005,
Please send me an example of a page with such accounts, and I'll see is it possible to integrate it or not.

**Comment by makusu2005** [comment]
Thanks for your response! For example, if you go to this page:
https://www.corvers.com/about-corvers/our-team and follow to links to every person it gives links to their linkedin pages on their individual pages i.e.
https://www.corvers.com/about-corvers/our-team/stephan-corvers

I found this regex for LI accounts: https://regex101.com/r/cI4gH9/1

Does that help? Let me know if I can do anything :)

**Comment by makusu2005** [comment]
Did you have time to look into this? 💯

**Comment by makusu2005** [comment]
No luck here?

**Comment by dmitriiweb** [comment]
Hi @makusu2005 , Please check this [example](https://dmitriiweb.github.io/extract-emails/code/factories/#extract_emails.factories.default_filter_and_email_and_linkedin.DefaultFilterAndEmailAndLinkedinFactory)
