### ISSUE TITLE
Setup.py install fail

### ISSUE THREAD

**Issue by SVD6** [dmitriiweb/extract-emails#2]
Hey, hope you find this as I'm really using your tool for an important project of mine.

I've been trying many ways to run "pip install extract_emails" and I even tried running setup.py but they all give me this same error: 

![image](https://user-images.githubusercontent.com/22820864/53096661-a9ab9a80-34ed-11e9-9834-ee99cd47b968.png)

![image](https://user-images.githubusercontent.com/22820864/53096626-96003400-34ed-11e9-85d9-5e311f5bc0f1.png)

I tried so far with Python 3.7, then after 3.6 as I realized that's what the requirements showed, but still same results. I've tried many different solutions but none have worked so far, do you think you could help me out with this?

**Comment by dmitriiweb** [comment]
Hello @SVD6,
Sorry for the late answer.
I think the problem was in fake_user_agent library, which I've used. Please try the new version.
Best regards,
Dmitrii.
