### ISSUE TITLE
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

### ISSUE THREAD

**Issue by FormationGrowthHacking** [dmitriiweb/extract-emails#5]
Hi,

Again, thanks for your job. It am experimenting it before to scale. It is great but I get issue when it doesn't find emails obviously.

I run this simple script for testing:
```
from extract_emails import ExtractEmails


em = ExtractEmails("http://www.formationgrowthhacking.com/", depth=None, print_log=False, ssl_verify=False, user_agent=None, request_delay=0.0)
emails = em.emails

print(emails)

```

I get these errors:

> Traceback (most recent call last):
>   File "C:/Users/Nino/PycharmProjects/EmailVerif/github_extract-email/extract_emails/myextrator.py", line 4, in <module>
>     em = ExtractEmails("http://www.formationgrowthhacking.com/", depth=None, print_log=False, ssl_verify=False, user_agent=None, request_delay=0.0)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 30, in __init__
>     self.extract_emails(url)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 43, in extract_emails
>     self.extract_emails(new_url)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 43, in extract_emails
>     self.extract_emails(new_url)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 43, in extract_emails
>     self.extract_emails(new_url)
>   [Previous line repeated 30 more times]
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 36, in extract_emails
>     self.get_all_links(r.text)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 59, in get_all_links
>     tree = html.fromstring(page)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\venv\lib\site-packages\lxml\html\__init__.py", line 875, in fromstring
>     doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\venv\lib\site-packages\lxml\html\__init__.py", line 761, in document_fromstring
>     value = etree.fromstring(html, parser, **kw)
>   File "src\lxml\etree.pyx", line 3234, in lxml.etree.fromstring
>   File "src\lxml\parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
> ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Could you please help me to fix this issue?

**Comment by dmitriiweb** [comment]
Please update the package

**Comment by FormationGrowthHacking** [comment]
Thanks. I did:

> Successfully installed extract-emails-3.0.3

But I  get these errors:

> Traceback (most recent call last):
>   File "C:/Users/Nino/PycharmProjects/EmailVerif/github_extract-email/extract_emails/myextrator.py", line 4, in <module>
>     em = ExtractEmails("http://www.formationgrowthhacking.com/", depth=None, print_log=False, ssl_verify=True, user_agent=None, request_delay=0.0)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 30, in __init__
>     self.extract_emails(url)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 43, in extract_emails
>     self.extract_emails(new_url)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 43, in extract_emails
>     self.extract_emails(new_url)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 43, in extract_emails
>     self.extract_emails(new_url)
>   [Previous line repeated 30 more times]
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 36, in extract_emails
>     self.get_all_links(r.text)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\github_extract-email\extract_emails\extract_emails.py", line 59, in get_all_links
>     tree = html.fromstring(page)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\venv\lib\site-packages\lxml\html\__init__.py", line 875, in fromstring
>     doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
>   File "C:\Users\Nino\PycharmProjects\EmailVerif\venv\lib\site-packages\lxml\html\__init__.py", line 761, in document_fromstring
>     value = etree.fromstring(html, parser, **kw)
>   File "src\lxml\etree.pyx", line 3234, in lxml.etree.fromstring
>   File "src\lxml\parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
> ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

I verified if new version was updated correctly in my pycharm:
http://prntscr.com/ou4srz

And it did.

**Comment by dmitriiweb** [comment]
Please update one more time

**Comment by FormationGrowthHacking** [comment]
Thanks. I don't get the error msg anymore.
