### ISSUE TITLE
Not picking up .co.uk email addresses correctly

### ISSUE THREAD

**Issue by darcohen** [dmitriiweb/extract-emails#7]
The ExtractEmails function is returning email addresses as ".co" and not ".co.uk". This may be an issue with the regex?

Example URL: http://www.aubreypark.co.uk/

**Comment by darcohen** [comment]
Perhaps this: r'[\w\.-]+@[\w\.-]+(?:\.[\w]+)+'

See: https://stackoverflow.com/questions/41798539/find-email-using-regular-expression-python

**Comment by SJMSNH** [comment]
Seems it only picks one . doesn't work for .gov.uk

**Comment by dmitriiweb** [comment]
@SJMSNH, please update to the last version
