### ISSUE TITLE
Depth scan

### ISSUE THREAD

**Issue by SJMSNH** [dmitriiweb/extract-emails#8]
How does the depth scan parameter works? I assumed that a parameter value of 1 will mean search www.example.com and 2 will mean www.example.com/contactus. But it doesn't seem to work, even the log says URLs = 1. Can you please help? Many thanks

**Comment by dmitriiweb** [comment]
@SJMSNH, Please update to the last version:
1. Use depth=0 to get emails only from example.com
2. Use depth=1 to get emails from example.com/contact
